name: repo_generation
description: A new Flutter project.
version: 0.0.2
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
#  analyzer: ^5.0.0
  build: ^2.4.1
  build_config: ^1.1.1
  code_builder: ^4.8.0
  repo_annotation:
    git:
      url: https://github.com/umidshox99/repo_annotation.git
  source_gen: ^1.2.2
#  meta: ^1.11.0

dev_dependencies:
  build_test: ^2.2.1
  build_runner: ^2.4.6




