name: repo_generation
description: A new Flutter project.
version: 0.0.2
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^5.0.0
  build: ^2.3.0
  build_config: ^1.0.0
  code_builder: ^4.1.0
  collection: ^1.15.0
  repo_annotation:
    git:
      url: https://github.com/umidshox99/repo_annotation.git
  meta: ^1.7.0
  source_gen: ^1.2.2
  strings: ^0.2.1

dev_dependencies:
  build_test:
  build_runner: ^2.4.6




