name: repo_generation
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen:
  repo_annotation:
    git:
      url: https://github.com/umidshox99/repo_annotation.git

dev_dependencies:
  build_test:
  build_runner:
  flutter_test:
    sdk: flutter




