name: repo_generation
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  source_gen: ^1.3.2
  repo_annotation:
    git:
      url: https://github.com/umidshox99/repo_annotation.git

dev_dependencies:
  build_test:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter




